### ISSUE TITLE
IDX Account Type Correction

### ISSUE THREAD

**Issue by allen-mcnichols** [idxbroker/wordpress-plugin#107]
idx\idx-api.php

Line 648 
needs to be changed to:

if (gettype($account_type) !== 'object' && $account_type[0] === 'IDX Broker Platinum Legacy') {

Otherwise all previous Platinum accounts show Upgrade Account in the Admin.

**Comment by csjoblom** [comment]
Good catch @allen-mcnichols we'll work on getting this patched up.

**Comment by ralls** [comment]
Thanks @allen-mcnichols 👍

**Comment by ErikIDX** [comment]
Fixed in #108
