### ISSUE TITLE
Improve Widget Class Names on Output

### ISSUE THREAD

**Issue by bhubbard** [idxbroker/wordpress-plugin#11]
Currently any IDX Broker widgets get class names such as these when displayed:

```
widget widget_353_39861
```

It would be useful if we had at least one more class name in there to help developers style themes for the IDX Broker widgets:

```
widget idxbroker-widget widget-353-39861
```

**Comment by antonioortegajr** [comment]
Closing this as the output for classes was changed in a previous release.
Example:
 class="widget  widget impress-showcase-widget" and the class containing a widget ID was removed for the IMPress widgets.
For widgets imported from the API the class structure was also updated and  class containing a widget ID was removed.
Example: class="IDX-quicksearchWrapper"
