### ISSUE TITLE
Security - Processing form data without nonce verification.

### ISSUE THREAD

**Issue by allen-mcnichols** [idxbroker/wordpress-plugin#114]
# Description

Anytime when processing form data it is best practice to validate that data before processing it by using a one time nonce to prevent data injection.

## Steps to Reproduce

/idx/wrapper.php
public function idx_ajax_create_dynamic_page() {

		// default page content.
		$post_content = $this->does_theme_include_idx_tag();
		$post_title = $_POST['post_title'] ? $_POST['post_title'] : 'Properties';

**Expected behavior:** When processing data from the $_POST array we should be validating that submission

**Actual behavior:** No validation is processed allowing for data injection

## Versions

Please fill out the following version information:
WordPress version: N/A
PHP version: N/A
IMPress plugin version: any

**note:** I am currently going through the plugin to address WordPress coding standards and will note this issue number within the wrapper.php script.

**Comment by NSHouseCat** [comment]
Resolved in version 2.6.2
