### ISSUE TITLE
One Omnibar Widget

### ISSUE THREAD

**Issue by bhubbard** [idxbroker/wordpress-plugin#13]
I think its more confusing to have two omnibar widgets. We should just have just one omnibar widget, with a checkbox option in the widget to display the extra fields. 

Even better if we make it a checkbox option for each field we might want to display. Example: 
- [ ] Price Max
- [ ] Beds
- [ ] Baths

**Comment by csjoblom** [comment]
I put in an enhancement request for this consolidation.

**Comment by antonioortegajr** [comment]
This could be an addition to the exisiting omni bar widget, but getting rid of the omni bar would be a breaking change for users currently using this widget. Backwards compatibility should be considered here.

**Comment by bhubbard** [comment]
I agree backwards compatibility is an issue. That is why I suggest it is done in stages.

Stage 1: 
Add all the options (including #31, which was just suggested) to what will become the single omnibar widget. Add a message on the old omnibar widget encouraging users to switch to the new omnibar widget

Stage 2:
Introduce some quick internal reporting/stats to find out how many sites still have the old widget in use, and how many times. Email all site owners/partners who need to update.

Stage 3:
In some future update kill the old widget with a notice, if possible programmatically replace it with the new widget

**Comment by bhubbard** [comment]
We have quite a bit of requests for the omnibar widget(s), somewhat related to this request, maybe someone can setup a label for them so we can group the issues. Then they can all be considered and addressed at the same time.

#39, #40, #41, #31, #13

**Comment by csjoblom** [comment]
@bhubbard I added the omnibar label.
