### ISSUE TITLE
Add option to settings page for Partner API Key

### ISSUE THREAD

**Issue by bhubbard** [idxbroker/wordpress-plugin#14]
The settings page should be updated to include the option to set the Partner API Key. The Partner API Key could be used to increase the API Limits, and possibly more options/features in the future.

**Comment by antonioortegajr** [comment]
While the partner key could increase the number of API calls the plugin makes, the actual number of calls being made has gone down in recent version due to handling caching a little differently. So it's tough to see storing this key now when nothing in the plugin will make use of it.

**Comment by csjoblom** [comment]
Going to close this for now, if we revisit it in the future it will be in the changelog.

**Comment by bhubbard** [comment]
@antonioortegajr @csjoblom 

While what you say makes sense, a couple things to consider:

1) While API calls are down now, it does not mean they could increase in the future. Also it is possible a website could incur an issue that causes it to quickly hit the API limit. As a developer partner we came across this issue once or twice on custom code, where we quickly used the partner api to increase the limit and then troubleshooted to find the problem. 

2) Adding the option in the plugin, it sets a standard for all IDX partners to save the key in the same place. Should multiple developers want to release a plugin or code that uses the Partner API Key they could all call it from the same source. This prevents having the key saved in multiple options due to multiple plugins or themes. 

3) The plugin could offer new features if the option to save the partner key is added. For example, a dashboard widget could display the client's lead count for the month, but also compare it to other clients under that partners account.
