### ISSUE TITLE
Improve API Input Box on Settings Page

### ISSUE THREAD

**Issue by bhubbard** [idxbroker/wordpress-plugin#19]
I suggest we improve the API Input box on the settings page by making two small changes:

1) Hide the API Key, we can do this simply by changing the input box from `type="text"` to `type="password"`.

2) We should increase the size of the input box just a bit, by adding the following to the input box:
```
size="40"
```

**Comment by amcn84** [comment]
We have it this way for troubleshooting purposes. The API key could be entered incorrectly and the only way to tell without repeating the process of activation is to compare the IDX Broker account -> API Control page to the initial settings page of WordPress.
