### ISSUE TITLE
Improve IDX Broker Options

### ISSUE THREAD

**Issue by bhubbard** [idxbroker/wordpress-plugin#25]
Right now the IDX Broker plugin stores several different options. I think we can merge some of them into one option and serialize the data. Yoast SEO is a good example with its `wpseo` option. I propose a new option called `idxbroker`. Again I suggest `idxbroker` vs `idx` as is more unique, and therefore less likely to run into conflicts. 

In this option we would start by storing the following:

`version` = Version of the plugin
`apikey` = Clients API Key
`partner_key` = The Partner's API Key
`api_version` = Version of API being used

**Comment by antonioortegajr** [comment]
Marking this as a won't do as this change would also impact the equity framework and any other plugin depending on where the current values are stored.
