### ISSUE TITLE
Delete legacy options on uninstall

### ISSUE THREAD

**Issue by bhubbard** [idxbroker/wordpress-plugin#28]
I sometimes come across clients are sites that still have the legacy data stored in the db. We should be deleting these on uninstall:

```
idx_broker_cid
idx_broker_basicSearchLink
idx_broker_advancedSearchLink
idx_broker_mapSearchLink
idx_broker_addressSearchLink
idx_broker_listingSearchLink
idx_custom_Homes_and_Cabins
etc
```

**Comment by antonioortegajr** [comment]
uninstall.php was added to the plugin in a previous commit. Closing this issue
