### ISSUE TITLE
System Links & Saved Links should be separate Custom Post Types

### ISSUE THREAD

**Issue by bhubbard** [idxbroker/wordpress-plugin#34]
As the IDX Broker system separates out system links and saved links, it makes more sense to have them as separate custom post types in WordPress. 

For example systemlinks have categories, while saved links have different categories. By separating them out we can support the categories. Example screenshot: https://cloudup.com/cUsSlvAllka

**Comment by amcn84** [comment]
Is this the same as https://github.com/idxbroker/wordpress-plugin/issues/24 ?

**Comment by bhubbard** [comment]
Yep, sorry, they are the same, closing this issue.
