### ISSUE TITLE
Offices Custom Post Type

### ISSUE THREAD

**Issue by bhubbard** [idxbroker/wordpress-plugin#35]
We should introduce offices as a Custom Post Type.

**Comment by amcn84** [comment]
Could you expand on this a bit? If I'm inferring correctly bring the Office roster page (a system link) in as a custom post type? Similar to: https://github.com/idxbroker/wordpress-plugin/issues/24

**Comment by bhubbard** [comment]
No, this is not similar to #24, but similar to #33.

Just like Featured Properties, I think Offices should be pulled from the API and then saved as a custom post type in WordPress. 

This would open many features:
* WP users can see a list of offices in WP Dashboard
* Offices can be found via WordPress default search
* Offices can be displayed via custom templates
* Developers can use standard WordPress functions to pull info about offices
* etc

Again, I provide a quick glance at how this would work in this video: https://dl.dropboxusercontent.com/u/782569/idxbrokerplugin-demo.mp4
