### ISSUE TITLE
Fontawesome currently loads via @import

### ISSUE THREAD

**Issue by bhubbard** [idxbroker/wordpress-plugin#4]
Currently FontAwesome is loaded via the omnibar code via a css import. It should be loaded thru wp_enqueue_style() so that developers have the ability to remove it from the page, or prevent it from loading twice. 

https://github.com/idxbroker/wordpress-plugin/blob/master/idx-broker-platinum/assets/css/idx-omnibar.css#L1

https://github.com/idxbroker/wordpress-plugin/blob/master/idx-broker-platinum/assets/css/idx-omnibar.min.css#L1

**Comment by AlphaBlossom** [comment]
+1 I was going to mention this as well. I use font awesome a lot and because of the @import it's being loaded twice.

**Comment by sheparddw** [comment]
This will be fixed in a future version of the plugin. However, the version number will be appended to the handle as it will require the 4.3.0 version of font awesome to display correctly.

**Comment by bhubbard** [comment]
Can we please not close this issue until the fix is in place?
