### ISSUE TITLE
OmniBar extra fields - bath step should be 0.50 not 0.01

### ISSUE THREAD

**Issue by savvyjackie** [idxbroker/wordpress-plugin#44]
Currently: `<input class="idx-omnibar-bath" type="number" min="0" step="0.01" title="Only numbers and decimals are allowed">`

Should be: `<input class="idx-omnibar-bath" type="number" min="0" step="0.50" title="Only numbers and decimals are allowed">`

**Comment by csjoblom** [comment]
Hi @savvyjackie, unfortunately some of the data that comes through are in non 0.5 denominations. This is the reasoning behind the 0.01.
