### ISSUE TITLE
Modify Search Button / Link Missing When Search Initiates with Widget

### ISSUE THREAD

**Issue by jdelia** [idxbroker/wordpress-plugin#45]
This seems like a crucial feature when using any IDX search widget, especially the Omnibar widget - if you are using the one WITHOUT the extra fields. 

Scenario:

Visitor enters zip code and presses Search from the home page Omnibar widget. The results page will need a modify search so they can refine it - entering min / max price, beds, baths, etc. and then run the search again. 

<img width="889" alt="screen shot 2016-01-28 at 9 05 51 am" src="https://cloud.githubusercontent.com/assets/3217274/12646490/6a158ad2-c59e-11e5-9cef-c4b818b7a938.png">

Without the Modify Search button / link - they must choose New Search or return to the home page widget and do what??? Search the zip code again? 

<img width="830" alt="screen shot 2016-01-28 at 9 06 01 am" src="https://cloud.githubusercontent.com/assets/3217274/12646494/73a11df0-c59e-11e5-8533-13e36be7e4e6.png">

This is how it looks if I can the url value for `widgetReferer` to false. Much better.
[http://savvyjackie.idxbroker.com/idx/results/listings?pt=sfr&widgetReferer=false](http://savvyjackie.idxbroker.com/idx/results/listings?pt=sfr&widgetReferer=false)

*_The  `&widgetReferer=true` in the url should not be controlling whether the Modify Search is displayed. That should be something we can configure within IDX Broker on the Results page option. *_

This is going to be a big issue for clients who want to use the Omnibar widget - my client is pointed this out and now does not want the Omnibar - after we spent time styling it for them.

**Comment by antonioortegajr** [comment]
This a great point and applies to more than just the plugin. Perhaps this should be true for all IDX widgets (except the map)?

**Comment by savvyjackie** [comment]
Yes exactly. I am sure this is an easy fix and will create a much richer user experience. That is the goal isn't it?

Jackie D'Elia
savvyjackiedesigns.com

**Comment by amcn84** [comment]
This is actually an issue with how the IDX search system functions and is going to be addressed there so that this will work for the majority of the widgets.

**Comment by antonioortegajr** [comment]
This issue would need to be fixed in the IDX core system not in wordpress. Closing this issue since it's not really a WP issue and passing to dev team at IDX.
