### ISSUE TITLE
Add layout support for Equity Framework

### ISSUE THREAD

**Issue by AlphaBlossom** [idxbroker/wordpress-plugin#54]
I'm having issues with IDX IMPress plugin wrappers not respecting the layout settings.

This issue was brought up earlier for the [Genesis framework](https://github.com/idxbroker/wordpress-plugin/issues/18#issue-116392021), but it doesn't seem to be working with Equity.

If I add Equity support for idx-wrapper, problem goes away:

`add_post_type_support( 'idx-wrapper', 'equity_site_layout' );`

**Comment by amcn84** [comment]
Make sure you are using the latest versions of the plugin and Equity framework.
Equity: 1.5.7
IMPress for IDX Broker: 2.1.0

**Comment by AlphaBlossom** [comment]
I am using the most up to date for both. Without the code above, it's not working for me. If you confirm it's working and the issue is on my end, you can close this out.

**Comment by antonioortegajr** [comment]
wrappers.php does say support of Equity layouts on line 69. This may have been added in a previous version. Closing this issue.
