### ISSUE TITLE
Duplicate IDX Pages when using wordpress import/export tools

### ISSUE THREAD

**Issue by kdanielleg** [idxbroker/wordpress-plugin#56]
When you use wordpress import/export on all content from one site with the plugin to another site with the plugin, it imports all of Site A's IDX pages into Site B. 

It even maintains the urls from site A. so (1) you end up with duplicate posts for all the default pages (though the second has the wrong url) along with any extra pages that were in Site A's account and (2) the urls on those pages match what was generated by Site A's plugin and dont match those generated by the plugin on Site B. 

At first, i thought that refreshing the plugin options would update the list to match only the pages in the currently connected account, but it doesnt. Since you guys have disabled the trash/delete capabilities for the idx pages post type in your plugin, there is no way to resolve this cleanly. 

Since i know wp custom post types, i just temporarily edited your plugin, removing the capabilities restrictions on the post type and deleting the duplicates, but really, the plugin should be comparing the IDX pages post type to some sort of master list generated by the api key and removing any pages that dont match

**Comment by amcn84** [comment]
We have a ticket in to address this in our next release.

**Comment by amcn84** [comment]
This should no longer be occurring after the last release. Please let me know if you are still experiencing this.

**Comment by kdanielleg** [comment]
seems to be resolved now, thanks!

On Thu, Jul 7, 2016 at 4:47 PM amcn84 <notifications@github.com> wrote:

> This should no longer be occurring after the last release. Please let me
> know if you are still experiencing this.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/idxbroker/wordpress-plugin/issues/56#issuecomment-231217252>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AR3iScOUS2JageOaVY-g-4-CiHgl1hdvks5qTXPWgaJpZM4ISqLp>
> .
>
-- 
*Kayla Griffin*
Owner, Web Design/Development



*"Lack of planning on your part does not constitute an emergency on my
part." *

M: 417-860-0653
O: 719-445-8909
Skype: kdanielleg
E: whatsup@kayladgriffin.com

http://kayladgriffin.com
http://idxwebsitepro.com
