### ISSUE TITLE
Allow usage of partner API key

### ISSUE THREAD

**Issue by sfgarza** [idxbroker/wordpress-plugin#58]
Currently the plugin does not give you the option to insert an IDX Broker partner API key to increase the hourly API limit

**Comment by AlisonLapidus** [comment]
+1

**Comment by WasaniP** [comment]
+1

**Comment by amcn84** [comment]
This method should only be used in custom plugins used by a developer to increase the limit for their individual customizations. The default limit of API calls is more than adequate for the number of API calls made by just the plugin. Adding this functionality to the plugin itself doesn't add much benefit to the plugin.

**Comment by sfgarza** [comment]
I have to respectfully disagree with that statement. I've come across a few of my clients sites that are using the plugin which continually hit the API limit. You can find more information on this in issue #57 

Additionally having the partner key available would be very beneficial during site development

**Comment by antonioortegajr** [comment]
Since client data can be manipulated using the partner key, IDX does not encourage the use of a partner key in areas clients may have access to. As this plugin is meant for client and partner use, the addition of a filed to store a partner key will not be added.
