### ISSUE TITLE
Map Widget fails to load on sites using HTTPS

### ISSUE THREAD

**Issue by bhubbard** [idxbroker/wordpress-plugin#60]
Hey guys, so maps will sometimes fail on sites using HTTPS. This is because the two of the scripts (`leaflet.js` & `leaflet-1.000.css`) loading don't support HTTPS. You can see them here:

https://github.com/idxbroker/wordpress-plugin/blob/cc4329b75f22fdb77c308931a67df6aa088a7653/idx/widgets/idx-widget-class.php#L61-L64

I see two options:

1: Add HTTPS support to your subdomain/cdn: `//idxdyncdn.idxbroker.com`. 

2: Load these two files from the plugin instead. With this option we could also serve minified versions of each file to improve performance.

**Comment by amcn84** [comment]
None of the IDX Broker widgets work across SSL. The IDX widgets themselves come from middleware and simply changing the protocol doesn't correct for the issue even more so if they use a custom sub domain. It's not as simple as just placing them in the CDN as they live within the individual accounts.

**Comment by bhubbard** [comment]
@amcn84 We use CloudFlare for some of our sites, which allows us to load the widgets over https, the only one that fails is the map widget due to the leaflet script & css being loaded from your CDN which doesn't support it. The CloudFlare plugin will replace `http://` with `//` which allows the widget to load over https just fine. Simply fixing these two files so they support https, or loading them via the plugin would fix the issue. CloudFlare is a popular service which I am sure others use, and can actually save you guys real money so it makes sense to support it.

**Comment by bhubbard** [comment]
@antonioortegajr Any thoughts on this?
