### ISSUE TITLE
Increments on Omnibar w/ Extra Fields number inputs

### ISSUE THREAD

**Issue by thestaceface** [idxbroker/wordpress-plugin#61]
The increments on the number inputs on the omnibar (min/max price, min beds, min baths) aren't very useful. In particular, the min baths increment is set to increase by 0.01, where 1 would make more sense. Price fields would be helpful if they incremented by 10000 (a suggestion) instead of 1.

**Comment by csjoblom** [comment]
Unfortunately due to the fact that we need to account for 600+ MLS data sets we need to account for half-baths, quarter-baths, and any other sort of bath increment that the various datasets provide. We can look into price fields though.
