### ISSUE TITLE
Noindex Issues

### ISSUE THREAD

**Issue by bhubbard** [idxbroker/wordpress-plugin#65]
So it appears that Google is no longer indexing IDX Pages for many sites. Looking into the issue I believe it has to do with the meta tag added by this plugin:

```<meta name='idx-robot'><meta name='robots' content='noindex,nofollow'>```

https://github.com/idxbroker/wordpress-plugin/blob/378b472d186f1902faf6d671725ed73854504b12/idx/initiate-plugin.php#L146

This code I know is suppose to be removed on all IDX pages, but it still exists. We need to make sure that ALL IDX Pages have the following tag:

```<meta name='robots' content='index,follow'>```

Other plugins like Yoast, All-In-One-SEO, Plugins that Minify code, etc can all change output of when and where the meta appears. We need to make sure that it always is set to index,follow. 

When I check the idx page bare the code doesn't exist, but when the wrapper is in play it does. 

From what I can tell this issue has been preventing all IDX pages from being indexed in Google for all clients using the IMPress for IDX Broker to create wrappers.

**Comment by antonioortegajr** [comment]
We add teh following to the wrapper page created by the WP plugin
<meta name='idx-robot'>
<meta name='robots' content='noindex,nofollow'>

The wrapper system looks for "<meta name='idx-robot'>" and removes this tag and the next line.

The reason this is done is so wrapper pages are not in SERPs and by using this line by line method, anyone wanting to use noindex still can. Minifiers or plugins that mutate the HTML are known to affect this.

**Comment by bhubbard** [comment]
Are you guys opening to making it a option to set the noindex, nofollow?

**Comment by davebonds** [comment]
I don't really see a reason why to add an additional option for such a limited use case. The wrapper system strips it out if it's formatted correctly. If you're using a plugin for minification that causes our system to not recognize the tag, then you should probably just not minify that page.

**Comment by bhubbard** [comment]
There are many plugins out there that perform minification and make other changes to wrappers. Minification is a valuable, especially since that code will be used on possibly ever idx page. 

Many clients are not even aware of this, nor do they have the skills to fix such an issue. Adding an option allows clients, developers a quick work-around. 

@davebonds 
How about re-structuring the code a bit so developers can easily disable or remove the tags with a filter?
