### ISSUE TITLE
Apply the widget_title filter to widget titles

### ISSUE THREAD

**Issue by Stephen-Cronin** [idxbroker/wordpress-plugin#69]
At the moment, the plugin outputs the widget titles without applying the `widget_title` filter. For example, the Carousel widget sets the title using this code (on line 360 of impress-carousel-widget.php):

```
$title = $instance['title'];
```

This mean that other plugins can't hook into the widget title. If you changed that line to:

```
$title = apply_filters( 'widget_title', $instance['title'] );
```

Then other plugins would be able to filter the titles of that widget.

Context: I wrote the [Remove Widget Titles plugin](https://wordpress.org/plugins/remove-widget-titles/) which hides the title if the user chooses to do so. One of your customers is trying to use it and came to me for support because it wasn't working (because of this issue).

I hope you're able to consider this for a future version. Thanks!

**Comment by antonioortegajr** [comment]
closed in PR #83
