### ISSUE TITLE
Cron Jobs causing issues with sites going down

### ISSUE THREAD

**Issue by yoursiteneedsme** [idxbroker/wordpress-plugin#70]
We are having an issue with our sites going down often and have been researching it to find out the cause. The underlying issue is that we have two plugins that are running too many repeating cron jobs. Jetpack and Impress. 

I am systematically removing Jetpack from all of our sites and replacing the specific functions that we use it for with alternate plugins. However I can not remove or replace IMPress. 

With Impress, the issue seems to be 2 cron jobs that run every 3 minutes:
idx_create_idx_pages
None
IDX\Idx_Pages->create_idx_pages()
2017-08-16 14:34:07 (1 minute)
3 minutes

idx_delete_idx_pages
None
IDX\Idx_Pages->delete_idx_pages()
2017-08-16 14:35:42 (2 minutes 35 seconds)
3 minutes

Since we are unfamiliar with these processes I wanted to touch base with you before we make any changes. 
Can you tell me exactly what these two cron jobs do? I am guessing that they are communicating between the site and IDXBroker to refresh the wrapper cache and/OR add & delete new wrappers that are created in the site. IMO, every 3 minutes seems like a lot and in fact is causing us issues when running 100 sites that use IDXBroker on our servers. 

I am not sure if suggesting that just refreshing the site cache and then refreshing the wrapper cache manually after creating or deleting a new wrapper page in IMPress should be enough instead of the widget doing it automatically every 3 minutes or adding an option to manually push this cron job inside the plugin like the option to Clear IDX Cache under Tools would work, but I wanted to put it out there as we need a solution to this. 

Alternately there is a plugin that we can use to edit these cron jobs WP Crontrol, which will allow me to edit & delete cron jobs. In your opinion can I use this plugin to make some alterations to try and to change them so that they are more manageable or would that be a bad idea?

**Comment by yoursiteneedsme** [comment]
Working with WPengine on this now - The technician I am working with (Brittani S.) did suggest that we should first address the autoloaded data and object caching and then manage the crons.

She suggests having autoloaded data set to no as opposed to yes within the database for those tables that don't need to be autoloaded then just keeping object cache within the WPEngine Utilities enabled. But before I do this she says I should make sure with you in case those rows do need to be autoloaded. In that case we will need to disable Object Caching and that may solve the problem. 

For example, our homesbycross install here is also exceeding that limit with 5,340,036 bytes where it should be under 800k. The top autloaded rows are going to be: 

4589071	idx_lead_cache
565673	idx_savedlinks_cache
33607	idx_postalcodes/combinedActiveMLS_cache
29245	idx_cities/combinedActiveMLS_cache
18663	idx_featured?disclaimers=true_cache
10223	idx_featured_cache
10223	idx_featured?disclaimers=true?disclaimers=true_cache

These examples above are currently set to yes and so that data is being loaded on every single page and then being stored in object cache and what is causing the 502s.

here is a list of sites that are throwing 502 errors:

250 502 homesbycross
242 502 benchmarkrealt
36 502 parklandfhomes
23 502 tampabayhomes4
17 502 sell4free
6 502 pacesfund
5 502 thehomebuyergu
4 502 finehomesmarin
4 502 auburnrealtor
3 502 rwyv
3 502 portaransastx
3 502 marcoareaexper
3 502 debbiebeasley
3 502 antiquemercant
2 502 visitbrentwood
2 502 teamwommack
2 502 prosoldrealty
2 502 oaklandjet


You can see this is effecting a lot of sites on my server. 

So here is an example of the processes: 

2-17 3669 84 127.0.0.1 yadkinvalleyrealestate.com:6789 POST /wp-cron.php?doing_wp_cron=1502998504.64474201202392578125
6-17 3699 82 127.0.0.1 visitbrentwood.wpengine.com:678 POST /wp-cron.php?doing_wp_cron=1502998507.36295294761657714843
7-17 3806 66 127.0.0.1 tampabayhomes4sale.net:6789 POST /wp-cron.php?doing_wp_cron=1502998522.95856189727783203125
10-17 4027 52 127.0.0.1 bodinhomepartn.wpengine.com:678 POST /wp-cron.php?doing_wp_cron=1502998536.94311594963073730468
9-17 4398 45 127.0.0.1 swflgulfcoast.wpengine.com:6789 POST /wp-cron.php?doing_wp_cron=1502998544.15806698799133300781
3:37 pm
The number right before the 127.0.0.1 is the number of seconds that it's been running.

**Comment by davebonds** [comment]
You can set those to not autoload and/or disable object caching if that will help resolve the issue.

We are looking into what could cause those options to be so large and how we may resolve this in a future update.

As for the cron jobs running every three minutes, those are only to check for and add/delete any new IDX pages and shouldn't be causing this current issue (unless there are a very large number of pages and/or saved links), and we will be addressing this in a future update as well.

**Comment by yoursiteneedsme** [comment]
I do have a large number of saved links with many clients. an you answer the other questions about using the plugin?

Alternately there is a plugin that we can use to edit these cron jobs WP Crontrol, which will allow me to edit & delete cron jobs. In your opinion can I use this plugin to make some alterations to try and to change them so that they are more manageable or would that be a bad idea?

**Comment by davebonds** [comment]
WP Crontrol is a great plugin. If that helps to manage the issue in the meantime, by all means, use it.

**Comment by yoursiteneedsme** [comment]
Thanks Dave - we turned off Object Caching on all of our sites and individually turned autoloading off in the databases for those tables as well on most of our sites. It seems to have fixed the issue for now. If we have any new issues I will let you know. Thanks for looking into this - we appreciate everything you do!!

**Comment by yoursiteneedsme** [comment]
Hi Dave,
I had this issue again today and it took down my entire server. I have looped WPEngine in on this support thread so they can comment as well and give you more insight. 

Has there been any movement on resolving this on your end by chance?

**Comment by bhubbard** [comment]
@yoursiteneedsme @davebonds IDX Broker should really update the plugin to use a background process library to solve this issue. Here are two good ones to choose from:

* https://github.com/wp-queue/wp-queue
* https://github.com/A5hleyRich/wp-background-processing

**Comment by yoursiteneedsme** [comment]
@bhubbard i have 77 sites down right now - what do i need to bribe you with to modify it for me

**Comment by bhubbard** [comment]
@yoursiteneedsme Want to reach out to me and/or @vinnylabarbera on Facebook or phone?

**Comment by csjoblom** [comment]
@antonioortegajr did we get this in with 2.5.7 release?

**Comment by antonioortegajr** [comment]
This issue was mitigated in the 2.5.7 release. With the addition of options for job frequency. Closing this issue.
