### ISSUE TITLE
Omnibar form won't submit in 2.4.1. Javascript error present.

### ISSUE THREAD

**Issue by LoganStrike** [idxbroker/wordpress-plugin#74]
After upgrading to 2.4.1, the Omnibar search form won't submit. Browser console shows the following error:

Uncaught ReferenceError: agentHeaderID is not defined
idx-omnibar.min.js?ver=4.9.2:1

**Comment by antonioortegajr** [comment]
Looks like this was fixed in commit bd22e0292634db08d8bf06dc287d4166e8efe021
