### ISSUE TITLE
On clean install, Impress dashboard metabox breaks menus and other metaboxes

### ISSUE THREAD

**Issue by LoganStrike** [idxbroker/wordpress-plugin#92]
On a clean WordPress install with IDX Impress plugin installed, the IDX Impress metabox on the admin Dashboard seems to cause all metaboxes after it to not render. In addition, the side admin menu does not show any dropdowns when hovering over parent links such as Appearance, Settings, etc.

When IDX Impress plugin is deactivated, these bugs are not present.

Steps to recreate:

1. Create a clean WP install.

2. Install and activate IDX Impress plugin. Don't update any settings.

3. Go to WordPress Dashboard. Metaboxes and admin menu are not working correctly.

**Comment by NSHouseCat** [comment]
This issue should be resolved now.
